### ISSUE TITLE
`- serverless-plugin-additional-stacks` ==> `- serverless-plugin-umzug`

### ISSUE THREAD

**Issue by josoroma-zz** [christophgysin/serverless-plugin-umzug#3]
I think there is a typo or something, you should change:

`- serverless-plugin-additional-stacks` by `- serverless-plugin-umzug` in:

https://github.com/christophgysin/serverless-plugin-umzug#configuration

Thanks!

**Comment by christophgysin** [comment]
Fixed in #1
